### ISSUE TITLE
How to add a map to a mosaic as an editor?

### ISSUE THREAD

**Issue by susannaanas** [wikimaps-dev/mapwarper#57] opened 2015-12-10 15:45 UTC
I am not finding the controls...

**Comment by timwaters** [comment] 2015-12-10 15:52
For Wikimaps Warper - Mosaics are Categories

Thus, add the map to the category in Commons and re-import the category. Any new maps will be added.

**Comment by susannaanas** [comment] 2015-12-10 15:57
In this case the map is in the category but it was imported before the category import. http://warper.wmflabs.org/maps/289

**Comment by timwaters** [comment] 2015-12-10 17:32
This issue has the description of a question which was answered, so I am closing this issue. I am also removing the bug label as it was a question, not a bug :)

I will create an additional issue to add individual maps to mosaics: #59 "Add ability to assign maps to mosaics within the warper"

**Comment by timwaters** [comment] 2015-12-10 17:33
(You can also add comments without the need to re-open the issue, just click the green button)

**Closed as completed by timwaters** 2015-12-10 17:32 UTC
Labels: question

**Comment by susannaanas** [comment] 2015-12-10 17:34
Thanks!
